### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Anonomous01** [Kr0ff/Pasta#2]
I have tried installing it but I get this message. 

Traceback (most recent call last):
  File "/root/Pasta/Pasta/./pasta.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Pasta/Pasta/./pasta.py", line 17, in <module>
    print(f"{attr(1)}{fg(1)}[-]{attr(0)} Some libraries are missing !")
NameError: name 'attr' is not defined

Is there anything I can do?
Thanks for the help and for making this project

**Comment by Kr0ff** [comment]
Hi,

The error is telling you that youre missing a library.

Please run

`python3 -m pip install -r requirements.txt
`

Within the folder of Pasta.
